---
# roles/system/tasks/main.yml

- name: Update all system packages (Debian/Ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == "Debian"

- name: Update all system packages (RHEL/Rocky)
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

